services:
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=M1S3Cr37P4s5w0rd
      - POSTGRES_DB=AuthDB
    container_name: authdb

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=secretsmanager,ssm
      - DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
      - '4571:4571'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/usr/local/etc/redis/redis.conf
